version: '3.4'

services:

    zookeeper:
        image: wurstmeister/zookeeper
        ports:
          - "2181:2181"
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000
          ZOOKEEPER_SYNC_LIMIT: 2
    kafka:
      image: wurstmeister/kafka
      command: [start-kafka.sh]
      ports:
        - 9094:9094
        - 9092:9092
      depends_on:
        - zookeeper
      environment:
              KAFKA_CREATE_TOPICS: "ingest_streaming_telemetry_tgr:1:1,ingest_syslogs_netdevice:1:1,vrfStats:1:1,test:1:1" # add new topics here appended with :1:1 for who knows why
              KAFKA_ADVERTISED_HOST_NAME: kafka # docker-machine ip
              KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
              KAFKA_ADVERTISED_PORT: 9092
              KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
              KAFKA_SASL_ENABLED_MECHANISMS: PLAIN
              KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
              KAFKA_LISTENERS: SASL_PLAINTEXT://:9092
              KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://localhost:9092
              KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"
      volumes:
        - "./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf"
